name: Binding Transition to Superseded
description: |
  Use this template to submit a binding transition to superseded state, i.e., a new binding whose state is current is replacing this one
labels: ["binding-transition-superseded"]
title: Provide the name and the version of the Binding, e.g. "Web of Things (WoT) HTTP Binding v2024-07-26"
body:
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Thank you for submitting the binding transition to superseded state. Please provide the information in this template for the custodian to review the transition. If a newer version of the binding is not available, please submit a transition to obsolete state instead. Superseded state indicates that a newer version of the binding is available.
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Please make sure to comply with our Code of Conduct (https://www.w3.org/policies/code-of-conduct/).
        It defines expected and unacceptable behaviors and promotes high standards of professional practice.
        The custodian is encouraged to apply necessary measures when necessary.
  - type: input
    id: name
    attributes:
      label: Name and Version of the Binding
      description: |
        Examples: Web of Things (WoT) HTTP Binding v2024-07-26, Web of Things (WoT) CoAP Binding v2024-07-26
    validations:
      required: true
  - type: input
    id: link-old
    attributes:
      label: Link to the binding document that is superseded
      description: |
        The exact link from the registry table which you want to transition to superseded state.
    validations:
      required: true
  - type: input
    id: link-new
    attributes:
      label: Link to the new binding document that supersedes the previous one
      description: |
        The exact link from the registry table which is the new binding that supersedes the previous one.
    validations:
      required: true
  - type: dropdown
    id: submitter-relationship
    attributes:
      label: Relationship to the Submitter
      description: |
        Are you related to the original submitter of the binding you want to transition to superseded state?
      options:
        - label: Yes, I am the original submitter or an authorized representative
        - label: No, I am not related to the original submitter
    validations:
      required: true
