name: Binding Transition to Current
description: |
  Use this template to submit a binding transition to current state, i.e., recommended for new implementations and it has enough implementation experience
labels: ["binding-transition-current"]
title: "Binding Transition to Current"
body:
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Thank you for submitting the binding transition to current state. 
        Please provide the information in this template for the custodian to review the transition. 
        Current state indicates that the binding is recommended for new implementations and it has enough implementation experience.
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Please make sure to comply with our Code of Conduct (https://www.w3.org/policies/code-of-conduct/).
        It defines expected and unacceptable behaviors and promotes high standards of professional practice.
        The custodian is encouraged to apply necessary measures when necessary.
  - type: input
    id: name
    attributes:
      label: Name and Version of the Binding
      description: |
        Examples: Web of Things (WoT) HTTP Binding v2024-07-26, Web of Things (WoT) CoAP Binding v2024-07-26
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to the binding document
      description: |
        The exact link from the registry table which you want to transition to current state.
    validations:
      required: true
  - type: dropdown
    id: submitter-relationship
    attributes:
      label: Relationship to the Submitter
      description: |
        Are you related to the original submitter of the binding you want to transition to current state?
      options:
        - label: Yes, I am the original submitter or an authorized representative
        - label: No, I am not related to the original submitter
    validations:
      required: true
  - type: input
    id: archive-link
    attributes:
      label: Archival Link
      description: |
        Link to the email sent to the https://lists.w3.org/Archives/Public/www-archive/ . Only required by submitters that cannot guarantee the stability of the link to the binding.
    validations:
      required: false
  - type: input
    id: link-test-report
    attributes:
      label: Link to the test report
      description: |
        The link to the test report that demonstrates the binding has enough implementation experience. 
        Please refer to https://w3c.github.io/wot-binding-registry/#req-trancurr for more details on the test report requirements.
    validations:
      required: true
