name: New Binding Submission
description: |
  Use this template to submit a new binding to the registry, going to the initial state
labels: ["new-binding"]
title: "New Binding Submission"
body:
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Thank you for submitting a new binding. The fields in this template fill the entry 
        format requirements set at https://w3c.github.io/wot-binding-registry/#entry-format.
        The binding document itself should have the content required at 
        https://w3c.github.io/wot-binding-registry/#submission-requirements
  - type: markdown
    attributes:
      value: |
        > [!Note]
        Please make sure to comply with our Code of Conduct (https://www.w3.org/policies/code-of-conduct/).
        It defines expected and unacceptable behaviors and promotes high standards of professional practice.
        The custodian is encouraged to apply necessary measures when necessary.
  - type: input
    id: name
    attributes:
      label: Name of the Binding
      description: |
        Examples: Web of Things (WoT) HTTP Binding, Web of Things (WoT) CoAP Binding
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to the binding document
      description: |
        Stable link whose content cannot change (e.g., a date, version number, etc.), 
        which can be managed by another entity than the custodian.
        Examples: `https://www.w3.org/TR/wot/binding-templates/http-20240726/index.html`
    validations:
      required: true
  - type: input
    id: binding-target
    attributes:
      label: Specification that the Binding Targets
      description: |
        The name and link of the specification that the binding is designed to target.
        Example: `MQTT 3.1.1 (https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html)`
    validations:
      required: true
  - type: input
    id: prefix
    attributes:
      label: Binding Prefix
      description: |
        Examples: `htv`, `modv`, `cov`
    validations:
      required: true
  - type: textarea
    id: identification
    attributes:
      label: Binding Identification
      description: |
        URI Scheme or other TD terms reserved for this binding, each provided as a new line.
        Examples: "subprotocol":"sse", "href":"http://example.com", "contentType":"application/json"
    validations:
      required: true
  - type: checkboxes
    id: td-version
    attributes:
      label: Supported TD version
      description: A binding SHOULD correspond to specific TD specification version(s).
      options:
        - label: V1.0
        - label: V1.1
        - label: V2.0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Binding Version
      description: |
        A string that identifies a specific version of this binding. Different bindings may share the same version string, but each version of a binding MUST be unique within that binding's history.
        The version string SHOULD contain a UTC-based date in ISO 8601 format in the form of YYYY-MM-DD.
    validations:
      required: true
  - type: input
    id: submitter
    attributes:
      label: Submitter Name and Contact
      description: |
        The name, and contact information of the submitting person of this binding. If you do not wish to make your email public, please send it as an email to TODO. See the next field about the organization behind. This will not be visible in the registry.
        Examples: `Jane Doe, Example Corp, jane.doe@example.com`
    validations:
      required: true
  - type: textarea
    id: binding-organization
    attributes:
      label: Organization Name and Contact
      description: |
        The organization name and contact information of the organization representing the binding specification. This information is used to contact for any transitions of the entry. If this does not apply to the binding, please provide explanation. This will not be visible in the registry.
        Examples: `ACME Standardization, contact@acme-standards.com`
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary of the Binding
      description: |
        Provide summary about the binding. 
        The content must comply with https://w3c.github.io/wot-binding-registry/#req-summ
        You can fill in the fields in the text field below using the template provided at https://github.com/w3c/wot-binding-registry/blob/main/SummaryExample.md
      value: |
        #### Abstract

        #### Examples

        #### Access and Usage Restrictions

        #### Dependent Bindings

        #### Available machine-readable documents (Schema, Ontology, JSON-LD Context)

        #### Link to the previous summary document
        (if available)

        #### Explanation about the versioning and ordering mechanism
        (if relevant)

    validations:
      required: true
